stages:
  - audit
  - cleanup

variables:
  GITLAB_URL: $GITLAB_URL
  ACCESS_TOKEN: $ACCESS_TOKEN
  PYTHONUNBUFFERED: 1  # 确保Python输出不会被缓冲

before_script:
  - pip3 install --upgrade pip
  - pip3 install aiohttp panda
  
audit_changes:
  stage: audit
  script:
    - python3 ultimate_logs.py
  artifacts:
    paths:
      - code_changes.csv
      - mr_reviews.csv
      - cicd_pipelines.csv
      - cicd_changes.csv
      - audit_records.csv
      - all_system_changes.csv
    expire_in: 1 week
  only:
    - schedules
    - web
  when: manual
  tags:
    - local-runner

cleanup:
  stage: cleanup
  script:
    - rm -f code_changes.csv mr_reviews.csv cicd_pipelines.csv cicd_changes.csv audit_records.csv all_system_changes.csv
  dependencies:
    - audit_changes
  only:
    - schedules
    - web
  when: manual
  tags:
    - local-runner
